version: '3.6'
services:
  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_PASSWORD: postgrespassword
    volumes:
      - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v1.3.3.cli-migrations-v2
    ports:
      - '8080:8080'
    depends_on:
      - 'postgres'
    restart: always
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ADMIN_SECRET: myhasurasecretkey
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS256", "jwk_url": "http://auth-backend:3000/auth/jwks"}'
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
  auth-backend:
    image: nhost/hasura-backend-plus:latest
    ports:
      - '3000:3000'
    restart: always
    environment:
      SERVER_URL: http://localhost:3000
      HASURA_ENDPOINT: http://graphql-engine:8080/v1/graphql
      HASURA_GRAPHQL_ADMIN_SECRET: myhasurasecretkey
      JWT_ALGORITHM: RS256
      S3_ENDPOINT: http://minio:9000
      S3_BUCKET: sqila 
      S3_ACCESS_KEY_ID: minio_access_key
      S3_SECRET_ACCESS_KEY: minio_secret_key
      AUTO_MIGRATE: 'false'
      COOKIE_SAME_SITE: lax
      COOKIE_SECURE: 'false'
      DEFAULT_USER_ROLE: user
  minio:
    image: minio/minio
    restart: always
    environment:
      S3_BUCKET: sqila
      MINIO_ACCESS_KEY: minio_access_key
      MINIO_SECRET_KEY: minio_secret_key 
    entrypoint: sh
    command: "-c 'mkdir -p /export/sqila && /usr/bin/minio server /export'"
    volumes:
      - 'minio_data:/data'
volumes:
  db_data:
  minio_data:
